create or replace PACKAGE PKG_CONST AS
    -- 適用徴収
    TYPE t_field_list01 IS TABLE OF VARCHAR2(4000);
    C_FIELD01_LIST t_field_list01 := t_field_list01('VW_IKOSAKI02');

    -- 領域
    NUM_FIELD01 CONSTANT  NUMBER := 1;
    NUM_FIELD02 CONSTANT  NUMBER := 2;
    NUM_FIELD03 CONSTANT  NUMBER := 3;
    NUM_FIELD04 CONSTANT  NUMBER := 4;
    NUM_FIELD05 CONSTANT  NUMBER := 5;
END PKG_CONST;